<?php
global $footer_right_menu_01;
global $footer_right_menu_02;
global $footer_right_menu_03;
global $footer_right_menu_04;
?>
<footer class="footer pt-3 ">
    <div class="container-fluid ">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-sm text-muted text-lg-start">
                    ©
                    <script>
                        document.write(new Date().getFullYear())
                    </script>
                    ,
                    made with <i class="fa fa-heart"></i> by
                    <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
                    for a better web.
                </div>
            </div>
            <div class="col-lg-6">
                <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                    <li class="nav-item">
                        <a href="#" class="nav-link text-muted" target="_blank"><?= $footer_right_menu_01; ?></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-muted" target="_blank"><?= $footer_right_menu_02; ?></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-muted" target="_blank"><?= $footer_right_menu_03; ?></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link pe-0 text-muted" target="_blank"><?= $footer_right_menu_04; ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>